/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DataLayer.AgentDB;
import DataLayer.AlienDB;
import DataLayer.InfoDB;
import Models.Agent;
import Models.IAgent;
import Models.IAlien;
import Models.IInfo;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import meninblack.AgentHantering;
import meninblack.AlienHantering;
import meninblack.InfoHantering;

/**
 *
 * @author hp
 */
public class RegistreraAliens extends javax.swing.JFrame {

    private Agent agent;
    private IInfo infoService = new InfoHantering(new InfoDB());
    private IAgent agentService = new AgentHantering(new AgentDB());
    private IAlien alienService = new AlienHantering(new AlienDB());
    /**
     * Creates new form RegistreraAliens
     */
    public RegistreraAliens(Agent agent) {
        initComponents();
        fyllAgentLista();
        fyllPlatsLista();
        this.agent = agent;
    }

    private RegistreraAliens() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void fyllAgentLista()
    {
        var agentLista = agentService.getAllaAgenter();
        DefaultListModel agenter = new DefaultListModel();
        jlAgentLista.setModel(agenter);
        for(int i = 0; i < agentLista.size(); i++)
        {
            agenter.add(i, agentLista.get(i).getNamn());
        }
    }
    
    public void fyllPlatsLista()
    {
        var platsLista = infoService.getAllaPlatser();
        DefaultListModel platser = new DefaultListModel();
        jlPlatsLista.setModel(platser);
        for (int i = 0; i < platsLista.size(); i++) 
        {
            platser.add(i, platsLista.get(i).getBenamning());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRegDatum = new javax.swing.JTextField();
        txtLosenord = new javax.swing.JTextField();
        txtNamn = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlAgentLista = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlPlatsLista = new javax.swing.JList<>();
        btnTillbaka = new javax.swing.JButton();
        btnSparaAlien = new javax.swing.JButton();
        btnValjAgent = new javax.swing.JButton();
        btnValjPlats = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtValdAgent = new javax.swing.JTextField();
        txtValdPlats = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ckbxBoglodite = new javax.swing.JCheckBox();
        ckbxWorm = new javax.swing.JCheckBox();
        ckbxSquid = new javax.swing.JCheckBox();
        txtAntalArmar = new javax.swing.JTextField();
        txtAntalBoogies = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtRegDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegDatumActionPerformed(evt);
            }
        });

        jLabel1.setText("Dagens datum");

        jLabel2.setText("Lösenord");

        jLabel3.setText("Namn");

        jLabel4.setText("Telefon");

        jlAgentLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlAgentLista);

        jlPlatsLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jlPlatsLista);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnSparaAlien.setText("Spara");
        btnSparaAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaAlienActionPerformed(evt);
            }
        });

        btnValjAgent.setText("Välj");
        btnValjAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValjAgentActionPerformed(evt);
            }
        });

        btnValjPlats.setText("Välj");
        btnValjPlats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValjPlatsActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Registrera ny Alien");

        jLabel6.setText("Ansvarig Agent");

        jLabel7.setText("Plats");

        txtValdAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValdAgentActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("Aliens ID väljs automatiskt");

        ckbxBoglodite.setText("BOGLODITE");

        ckbxWorm.setText("WORM");

        ckbxSquid.setText("SQUID");

        jLabel9.setText("Antal boogies");

        jLabel10.setText("Antal armar");

        jLabel11.setText("Välj Aliens Ras nedan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel5))
                    .addComponent(btnTillbaka)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRegDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnValjAgent)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtValdAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtValdPlats, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSparaAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(264, 264, 264))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ckbxBoglodite, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ckbxSquid, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ckbxWorm, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtAntalBoogies, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtAntalArmar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(btnValjPlats))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(ckbxBoglodite)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRegDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTillbaka)
                            .addComponent(btnSparaAlien)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtAntalBoogies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnValjAgent)
                                    .addComponent(btnValjPlats))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtValdAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValdPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(ckbxWorm)
                                .addGap(32, 32, 32)
                                .addComponent(ckbxSquid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAntalArmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRegDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegDatumActionPerformed

    private void btnSparaAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaAlienActionPerformed
        // TODO add your handling code here:
        int id = alienService.getMaxIDfromAlien();
        String regdatum = txtRegDatum.getText();
        String losenord = txtLosenord.getText();
        String namn = txtNamn.getText();
        String telefon = txtTelefon.getText();
        int ansvarigAgent = Integer.parseInt(txtValdAgent.getText());
        int plats = Integer.parseInt(txtValdPlats.getText());
        if(ckbxBoglodite.isSelected() && ckbxSquid.isSelected() && ckbxWorm.isSelected())
        {
            JOptionPane.showMessageDialog(null, "Alien kan inte tillhöra mer än en ras");
            return;
        }
        if(ckbxBoglodite.isSelected() && ckbxSquid.isSelected())
        {
            JOptionPane.showMessageDialog(null, "Alien kan inte tillhöra mer än en ras");
            return;
        }
        if(ckbxBoglodite.isSelected() && ckbxWorm.isSelected())
        {
            JOptionPane.showMessageDialog(null, "Alien kan inte tillhöra mer än en ras");
            return;
        }
        if(ckbxSquid.isSelected() && ckbxWorm.isSelected())
        {
            JOptionPane.showMessageDialog(null, "Alien kan inte tillhöra mer än en ras");
            return;
        }
        else if(ckbxBoglodite.isSelected())
        {
            alienService.SkapaAlien(id, regdatum, losenord, namn, telefon, plats, ansvarigAgent);
            int antalBoogies = Integer.parseInt(txtAntalBoogies.getText());
            alienService.registreraAlienSomBOGLODITE(id, antalBoogies);
            JOptionPane.showMessageDialog(null, namn + " är nu registrerad! han har automatiskt blivit tilldelad med ID-nummer: " + id);
            return;
        }
        else if(ckbxSquid.isSelected())
        {
            alienService.SkapaAlien(id, regdatum, losenord, namn, telefon, plats, ansvarigAgent);
            int antalArmar = Integer.parseInt(txtAntalArmar.getText());
            alienService.registreraAlienSomSQUID(id, antalArmar);
            JOptionPane.showMessageDialog(null, namn + " är nu registrerad! han har automatiskt blivit tilldelad med ID-nummer: " + id);
            return;
        }
        else if(ckbxWorm.isSelected())
        {
            alienService.SkapaAlien(id, regdatum, losenord, namn, telefon, plats, ansvarigAgent);
            alienService.registreraAlienSomWorm(id);
            JOptionPane.showMessageDialog(null, namn + " är nu registrerad! han har automatiskt blivit tilldelad med ID-nummer: " + id);
            return;
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Du måste välja Ras för Alien");
        }
        
        
    }//GEN-LAST:event_btnSparaAlienActionPerformed

    private void txtValdAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValdAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValdAgentActionPerformed

    private void btnValjAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValjAgentActionPerformed
        // TODO add your handling code here:
        var agentnamn = jlAgentLista.getSelectedValue();
        var agentIdString = agentService.getIDfromNamn(agentnamn);
        txtValdAgent.setText(agentIdString);
    }//GEN-LAST:event_btnValjAgentActionPerformed

    private void btnValjPlatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValjPlatsActionPerformed
        // TODO add your handling code here:
        var platsnamn = jlPlatsLista.getSelectedValue();
        var platsIdString = infoService.getIDfromPlats(platsnamn);
        txtValdPlats.setText(platsIdString);
    }//GEN-LAST:event_btnValjPlatsActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistreraAliens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistreraAliens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistreraAliens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistreraAliens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistreraAliens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSparaAlien;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JButton btnValjAgent;
    private javax.swing.JButton btnValjPlats;
    private javax.swing.JCheckBox ckbxBoglodite;
    private javax.swing.JCheckBox ckbxSquid;
    private javax.swing.JCheckBox ckbxWorm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> jlAgentLista;
    private javax.swing.JList<String> jlPlatsLista;
    private javax.swing.JTextField txtAntalArmar;
    private javax.swing.JTextField txtAntalBoogies;
    private javax.swing.JTextField txtLosenord;
    private javax.swing.JTextField txtNamn;
    private javax.swing.JTextField txtRegDatum;
    private javax.swing.JTextField txtTelefon;
    private javax.swing.JTextField txtValdAgent;
    private javax.swing.JTextField txtValdPlats;
    // End of variables declaration//GEN-END:variables
}
